---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
- name: redhat
  driver_config:
    box: redhat

suites:
- name: handler
  run_list:
  - recipe[simple_handler::default]
